{
 "title": "Open5GS_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "PCF", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PCF Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "fivegs_pcffunction_pa_sessionnbr",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCF SM associations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "fivegs_pcffunction_pa_policysmassoreq",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_pcffunction_pa_policysmassosucc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCF AM policy associations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "fivegs_pcffunction_pa_policyamassoreq{job=\"open5gs-pcf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_pcffunction_pa_policyamassosucc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCF Container metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"open5gs-pcf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"open5gs-pcf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_open_fds{job=\"open5gs-pcf-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SMF", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "SMF container metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"open5gs-smf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"open5gs-smf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_cpu_seconds_total{job=\"open5gs-smf-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GTP_v1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "gn_rx_createpdpcontextreq{job=\"open5gs-smf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gn_rx_deletepdpcontextreq{job=\"open5gs-smf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gtp1_pdpctxs_active{job=\"open5gs-smf-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GTP_v2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "gtp2_sessions_active{job=\"open5gs-smf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "s5c_rx_createsession{job=\"open5gs-smf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "s5c_rx_deletesession{job=\"open5gs-smf-metrics\"}",
     "legendFormat": "__auto"
    },
    { "expr": "s5c_rx_parse_failed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "N4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "fivegs_smffunction_sm_n4sessionestabreq{job=\"open5gs-smf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_smffunction_sm_n4sessionreport{job=\"open5gs-smf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_smffunction_sm_n4sessionreportsucc{job=\"open5gs-smf-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gtp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "gtp_new_node_failed{job=\"open5gs-smf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gtp_peers_active{job=\"open5gs-smf-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "general",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "ues_active{job=\"open5gs-smf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bearers_active{job=\"open5gs-smf-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "UPF", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "UPF gtp traffic over N3 in/out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "fivegs_ep_n3_gtp_indatapktn3upf",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_ep_n3_gtp_outdatapktn3upf",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "fivegs_upffunction_upf_sessionnbr",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF N4 sess + reports",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "fivegs_upffunction_sm_n4sessionestabreq",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_upffunction_sm_n4sessionreport",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_upffunction_sm_n4sessionreportsucc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF Qos Flows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "fivegs_upffunction_upf_qosflows",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF container metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"open5gs-upf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"open5gs-upf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_cpu_seconds_total{job=\"open5gs-upf-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AMF", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "AMF emergency registrations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "fivegs_amffunction_rm_regemergreq",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_amffunction_rm_regemergsucc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF init reg requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "fivegs_amffunction_rm_reginitreq",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_amffunction_rm_reginitsucc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UE Configuration update commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "fivegs_amffunction_mm_confupdate",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_amffunction_mm_confupdatesucc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# UE gNodeB AMF Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    { "expr": "ran_ue", "legendFormat": "__auto" },
    { "expr": "amf_session", "legendFormat": "__auto" },
    { "expr": "gnb", "legendFormat": "__auto" },
    {
     "expr": "fivegs_amffunction_rm_registeredsubnbr",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AFM paging",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "fivegs_amffunction_mm_paging5greq",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_amffunction_mm_paging5gsucc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF authentication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "fivegs_amffunction_amf_authreject",
     "legendFormat": "__auto"
    },
    { "expr": "fivegs_amffunction_amf_authreq", "legendFormat": "__auto" },
    {
     "expr": "fivegs_amffunction_amf_authfail",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Periodic registration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "fivegs_amffunction_rm_regperiodreq",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_amffunction_rm_regperiodsucc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mobility registration updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "fivegs_amffunction_rm_regmobreq",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_amffunction_rm_regmobsucc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF container metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "process_max_fds{job=\"open5gs-amf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"open5gs-amf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"open5gs-amf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_virtual_memory_max_bytes{job=\"open5gs-amf-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"amf\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_open_fds{job=\"open5gs-amf-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}