## Adjusted for:
## - container image version gradiant/ueransim:dev-b68de9b (tag dev-b68de9b)
## - four UEs (must be consistent with gnb deployment)

image:
  registry: docker.io
  repository: gradiant/ueransim
  tag: dev-b68de9b
  pullPolicy: Always
  pullSecrets: []
  debug: false

amf:
  hostname: open5gs-amf-ngap

gnb:
  hostname: ueransim-gnb

mcc: '999'
mnc: '70'
sst: 1
sd: "0x111111"
tac: '0001'

ues:
  enabled: true
  count: 4
  initialMSISDN: '0000000001'
