# Run server:
#  run deployment + kubectl 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
        - name: iperf3
          image: heywoodlh/iperf3:iperf3
          ports:
            - containerPort: 5201
